@host = https://localhost
@port = 7114

@RestaurantApi_HostAddress = https://localhost:7114

GET {{RestaurantApi_HostAddress}}/weatherforecast
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}}
RandomInt: {{$randomInt}}
# ProjectUrl: {{$projectUrl}}

###

GET {{RestaurantApi_HostAddress}}/weatherforecast/get2?count=3
Content-Type: application/json

{
  "min": "-23",
  "max": "23"
}
###
